src/Entity/Abonne.php
<?php

namespace App\Entity;

use App\Repository\AbonneRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AbonneRepository::class)
 */
class Abonne
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $prenom;

    /**
     * @ORM\Column(type="date")
     */
    private $date_inscription;

    /**
     * @ORM\OneToMany(targetEntity=Emprunt::class, mappedBy="abonne", orphanRemoval=true)
     */
    private $emprunts;

    public function __construct()
    {
        $this->emprunts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateInscription(): ?\DateTimeInterface
    {
        return $this->date_inscription;
    }

    public function setDateInscription(\DateTimeInterface $date_inscription): self
    {
        $this->date_inscription = $date_inscription;

        return $this;
    }

    /**
     * @return Collection|Emprunt[]
     */
    public function getEmprunts(): Collection
    {
        return $this->emprunts;
    }

    public function addEmprunt(Emprunt $emprunt): self
    {
        if (!$this->emprunts->contains($emprunt)) {
            $this->emprunts[] = $emprunt;
            $emprunt->setAbonne($this);
        }

        return $this;
    }

    public function removeEmprunt(Emprunt $emprunt): self
    {
        if ($this->emprunts->contains($emprunt)) {
            $this->emprunts->removeElement($emprunt);
            // set the owning side to null (unless already changed)
            if ($emprunt->getAbonne() === $this) {
                $emprunt->setAbonne(null);
            }
        }

        return $this;
    }

}

src/Entity/Emprunt.php
<?php

namespace App\Entity;

use App\Repository\EmpruntRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EmpruntRepository::class)
 */
class Emprunt
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date_emprunt;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_retour;

    /**
     * @ORM\ManyToOne(targetEntity=Abonne::class, inversedBy="emprunts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $abonne;

    /**
     * @ORM\ManyToOne(targetEntity=Livre::class, inversedBy="emprunts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $livre;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateEmprunt(): ?\DateTimeInterface
    {
        return $this->date_emprunt;
    }

    public function setDateEmprunt(\DateTimeInterface $date_emprunt): self
    {
        $this->date_emprunt = $date_emprunt;

        return $this;
    }

    public function getDateRetour(): ?\DateTimeInterface
    {
        return $this->date_retour;
    }

    public function setDateRetour(?\DateTimeInterface $date_retour): self
    {
        $this->date_retour = $date_retour;

        return $this;
    }

    public function getAbonne(): ?Abonne
    {
        return $this->abonne;
    }

    public function setAbonne(?Abonne $abonne): self
    {
        $this->abonne = $abonne;

        return $this;
    }

    public function getLivre(): ?Livre
    {
        return $this->livre;
    }

    public function setLivre(?Livre $livre): self
    {
        $this->livre = $livre;

        return $this;
    }
}

src/Form/AbonneType.php
<?php

namespace App\Form;

use App\Entity\Abonne;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class AbonneType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('prenom', TextType::class, [ "label" => "Prénom : ", "required" => true ])
            ->add('date_inscription', DateType::class, [ 
                "label" => "Date d'inscription : ",
                "widget" => "single_text"
            ])
            ->add("enregistrer", SubmitType::class)

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Abonne::class,
        ]);
    }
}

src/Controller/AbonneController.php
<?php

namespace App\Controller;

use App\Entity\Abonne;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\AbonneRepository;
use App\Form\AbonneType;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\EntityManagerInterface as EMI;

class AbonneController extends AbstractController
{
    /**
     * @Route("/abonne", name="abonne")
     */
    public function index()
    {
        return $this->render('abonne/index.html.twig', [
            'controller_name' => 'AbonneController',
        ]);
    }

    /**
     * @Route("/abonne/liste", name="liste_abonnes")
     */
    public function liste(AbonneRepository $abonneRepository){
        $liste_abonnes = $abonneRepository->findAll();
        return $this->render("abonne/liste.html.twig", compact("liste_abonnes"));
    }

    /**
     * @Route("/abonne/{id}", name="fiche_abonne", requirements={"id"="\d+"})
     */
    public function fiche(AbonneRepository $abonneRepository, $id){
        $abonne = $abonneRepository->find($id);
        return $this->render("abonne/fiche.html.twig", compact("abonne"));
    }

    /**
     * @Route("/abonne/ajouter", name="ajouter_abonne")
     */
    public function ajouter(Request $request, EMI $entityManager)
    {
        $abonne = new Abonne;
        $formulaire = $this->createForm(AbonneType::class, $abonne);
        $formulaire->handleRequest($request);
        if( $formulaire->isSubmitted() && $formulaire->isValid() ){
            $entityManager->persist($abonne);
            $entityManager->flush();
            return $this->redirectToRoute("liste_abonnes");
        }

        return $this->render("abonne/formulaire.html.twig", [ "formulaire" => $formulaire->createView() ]);
    }

        /**
     * @Route("/abonne/modifier/{id}", name="modifier_abonne", requirements={"id"="\d+"})
     */
    public function modifier(EMI $entityManager, Request $request, AbonneRepository $abonneRepository, int $id){
        $abonne = $abonneRepository->find($id);
        $formulaire = $this->createForm(AbonneType::class, $abonne);
        $formulaire->handleRequest($request);
        if( $formulaire->isSubmitted() && $formulaire->isValid() ){
            // $entityManager->persist($abonne);
            $entityManager->flush();
            return $this->redirectToRoute("liste_abonnes");
        }

        return $this->render("abonne/formulaire.html.twig", [ "formulaire" => $formulaire->createView() ]);

    }

    /**
     * @Route("/abonne/supprimer/{id}", name="supprimer_abonne", requirements={"id"="\d+"})
     */
    public function supprimer(EMI $entityManager, AbonneRepository $abonneRepository, int $id)
    {
        $abonne = $abonneRepository->find($id);
        // La méthode 'remove' crée une requête DELETE en attente
        $entityManager->remove($abonne);
        $entityManager->flush();
        return $this->redirectToRoute("liste_abonnes");
    }

}

templates/abonne/fiche.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <h1>Fiche Abonné</h1>
    <ul>
        <li>Prénom : {{ abonne.prenom }}</li>
        <li>Date d'inscription : {{ abonne.dateInscription|date("d/m/Y") }}</li>
    </ul>

    <div>
        <table>
            <thead>
                <tr>
                    <th>Livre</th>
                    <th>Emprunté le</th>
                    <th>Rendu le</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for emprunt in abonne.emprunts %}
                    <tr>
                        <td>{{ emprunt.livre.titre ~ " - " ~ emprunt.livre.auteur  }}</td>
                        <td>{{ emprunt.dateEmprunt|date("d/m/Y") }}</td>
                        <td>{{ emprunt.dateRetour is empty ? "" :emprunt.dateRetour|date("d/m/Y") }}</td>
                        <td>
                            <a href="{{ path("fiche_emprunt", { id: emprunt.id }) }}">fiche</a>
                            <a href="{{ path("modifier_emprunt", { id: emprunt.id }) }}">modifier</a>
                            <a href="{{ path("supprimer_emprunt", { id: emprunt.id }) }}" 
                                onclick="return confirm('Êtes-vous sûr de vouloir supprimer cet emprunt ?');">supprimer</a>
                        </td>
                    </tr>
                {% endfor %}
                <tr></tr>
            </tbody>
            <tfooter></tfooter>
        </table>
    </div>

    <a href="{{ path("liste_abonnes") }}">Retour liste</a>
{% endblock %}

templates/abonne/formulaire.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <h2>Formulaire Abonné</h2>
    {{ form(formulaire) }}
    
{% endblock %}

templates/abonne/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AbonneController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/xampp/htdocs/biblioSF4/src/Controller/AbonneController.php'|file_link(0) }}">src/Controller/AbonneController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/xampp/htdocs/biblioSF4/templates/abonne/index.html.twig'|file_link(0) }}">templates/abonne/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/abonne/liste.html.twig
{% extends "base.html.twig" %}

{% block body %}
<a href="{{ path("ajouter_abonne")}}">Ajouter</a>
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Prénom</th>
            <th>Date</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for abonne in liste_abonnes %}
            <tr>
                <td>{{ abonne.id }}</td>
                <td>{{ abonne.prenom}}</td>
                <td>{{ abonne.dateInscription|date("d/m/Y") }}</td>
                <td>
                   <a href="{{ path("fiche_abonne", { id: abonne.id }) }}">fiche</a>
                   <a href="{{ path("modifier_abonne", { id: abonne.id }) }}">modifier</a>
                   <a href="{{ path("supprimer_abonne", { id: abonne.id }) }}" onclick="return confirm('Êtes-vous sûr de vouloir supprimer cet abonné ?');">supprimer</a>
                </td>
            </tr>
        {% endfor %}
        <tr></tr>
    </tbody>
    <tfooter></tfooter>
</table>  
{% endblock %}